### ISSUE TITLE
Small UI Improvement 

### ISSUE THREAD

**Issue by bz-harshitha-alikepalli** [mbashem/cftracker#141]
Can have the nav bar sticky, and rerouting the users to homepage when CFTracker logo is clicked!!

![image](https://github.com/mbashem/cftracker/assets/137029816/94c84e4e-7834-4a4b-a7c6-8a40d9cf8baa)
![image](https://github.com/mbashem/cftracker/assets/137029816/dcc75d4b-b78c-4437-98b3-fa6bf9bf11e0)

**Comment by mbashem** [comment]
I think the current navigation is better than the sticky navigation bar. Also, if you click on the logo, it redirects you to the contest page.
