### ISSUE TITLE
 [Contest Page ] Allow multi select on contest type

### ISSUE THREAD

**Issue by kaushikkumarbz** [mbashem/cftracker#145]
<img width="963" alt="image" src="https://github.com/mbashem/cftracker/assets/65885903/ce585eb2-0449-48cf-99e4-91168855b7cc">

It can be a multi select dropdown

**Comment by mbashem** [comment]
Thanks for the suggestion. I will try to implement it.

**Comment by Kevin114514** [comment]
Please add this O.O

**Comment by mbashem** [comment]
I will try to implement it next month.

**Comment by mbashem** [comment]
It is implemented.  #170
