### ISSUE TITLE
[Suggestion] : Show CF API Status

### ISSUE THREAD

**Issue by prabh1601** [mbashem/cftracker#80]
First off, great website, one of the daily tools for me. So cheers for great work!

Coming to Suggestion, Often what happens is when API is down the website rather just turns out to be a white page. It might be beneficial for a user as a whole if you can put a disclaimer in the topbar whenever API is down like a red area maybe which shows "CF API down, cannot parse data" or something similar?

**Comment by mbashem** [comment]
I will try. But I don't think it will come anytime soon. Mostly for my laziness😓.

**Comment by mbashem** [comment]
From now, you will get notifications if the site fails to fetch the problems list or submissions.
