### ISSUE TITLE
The website crashes randomly

### ISSUE THREAD

**Issue by YOYO-UIAT** [mbashem/cftracker#90]
This website is really helpful, thank you for your great work. But sometimes it says "ERR_CONNECTION_CLOSED", and sometimes I can visit the website normally. Could you please fix it? Thanks.

**Comment by mbashem** [comment]
A quick google search tells me it is not related to the website but more of a device-related issue. I think [these methods](https://kinsta.com/knowledgebase/err_connection_closed/) may help.

**Comment by YOYO-UIAT** [comment]
It seems that after I changed my VPN, this problem disappears. Thanks.
