### ISSUE TITLE
About "More than 2"

### ISSUE THREAD

**Issue by YOYO-UIAT** [mbashem/cftracker#93]
In Global Round 24, there are three versions of problem G. In cftracker, it only shows "More than 2", and doesn't have different cells for each version. Can you fix it? Thanks!

**Comment by mbashem** [comment]
I haven't decided on how to render more than two problems yet, as rated contests previously didn't have three versions of the same problem. I will try to fix it as soon as possible.

**Comment by mbashem** [comment]
Fixed. The site now renders up to 3 versions of the same problem.

**Comment by YOYO-UIAT** [comment]
Thanks

**Comment by YOYO-UIAT** [comment]
But it seems that the status of the problem(accepted or attempted) is not shown
